name: Test & Lint
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: yarn --frozen-lockfile && yarn test
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get audits
        run: npx audit-ci -h
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ESLint
        run: yarn --frozen-lockfile && yarn eslint
      - name: Prettier
        run: yarn --frozen-lockfile && yarn prettier:check
